- name: Create PostgreSQL container
  docker_container:
    name: '{{ container_name }}'
    image: '{{ image }}'
    state: present
    ports: '{{ ports }}'
    volumes: '{{ volumes }}'
    restart_policy: unless-stopped
    env:
      POSTGRES_PASSWORD: '{{ postgres_password }}'
