- name: Create Kafka container
  docker_container:
    name: '{{ container_name }}'
    image: '{{ image }}'
    state: present
    ports: '{{ ports }}'
    volumes: '{{ volumes }}'
    restart_policy: unless-stopped
    env:
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'host.docker.internal:2181'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
