- name: Create MySQL container
  docker_container:
    name: '{{ container_name }}'
    image: '{{ image }}'
    state: present
    ports: '{{ ports }}'
    volumes: '{{ volumes }}'
    env:
      MYSQL_ALLOW_EMPTY_PASSWORD: "1"
